### ISSUE TITLE
error while using DeepSimulator 

### ISSUE THREAD

**Issue by dhallanjali** [realbigws/DeepSimulator#1]
while running ./deep_simulator.sh -i example/artificial_chr22.fasta i got the following error. 

Traceback (most recent call last):
  File "/home/anjalid/DeepSimulator/pore_model/src/kmer_simulator.py", line 135, in <module>
    kmer_poremodel=load_official_poremodel(arg.poremodel)
  File "/home/anjalid/DeepSimulator/pore_model/src/kmer_simulator.py", line 18, in load_official_poremodel
    data=pickle.load(f)
  File "/home/anjalid/miniconda2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/home/anjalid/miniconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/anjalid/miniconda2/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
TypeError: scalar() argument 1 must be numpy.dtype, not numpy.dtype

**Comment by realbigws** [comment]
Hi, Anjali.

This issue might due to the pickle version in your python. However, I have replaced the model file in '.pkl' with plain text.

Please 'git pull' the repository and try again.

Best,
-Sheng

**Comment by dhallanjali** [comment]
Hi Sheng,

I am facing issues while pulling it (git pull https://github.com/realbigws/DeepSimulator.git
fatal: not a git repository (or any of the parent directories): .git) please help me.

**Comment by realbigws** [comment]
just type
'git pull'

in the following directory:
/home/anjalid/DeepSimulator

**Comment by realbigws** [comment]
You may also need to type './install' for the first time.

**Comment by dhallanjali** [comment]
Hi, 
i am getting the following error when I type ' git pull '

remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 54 (delta 32), reused 42 (delta 20), pack-reused 0
Unpacking objects: 100% (54/54), done.
From https://github.com/realbigws/DeepSimulator
   b637de6..82d1fb3  master     -> origin/master
Updating b637de6..82d1fb3
error: Your local changes to the following files would be overwritten by merge:
	README.md
	deep_simulator.sh
	pore_model.sh
Please commit your changes or stash them before you merge.
Aborting

**Comment by realbigws** [comment]
Just remove the folder and install the whole repository again by 'git clone'

**Comment by dhallanjali** [comment]
I have done with 'git pull' 
(base) anjalid@c39129c41926:~/DeepSimulator$ git pull
Already up to date.
But, when I use the am testing it using './deep_simulator.sh -i example/artificial_human_chr22.fasta' command. I am facing a similar error. I have install numpy. Please, suggest me what can I do. to resolve this error. 

(base) anjalid@c39129c41926:~/DeepSimulator$ ./deep_simulator.sh -i example/artificial_human_chr22.fasta
Pre-process input genome...
Pre-process input genome done!
Executing the preprocessing step...
Traceback (most recent call last):
  File "/home/anjalid/DeepSimulator/util/genome_sampling.py", line 4, in <module>
    import numpy as np
ImportError: No module named numpy
./deep_simulator.sh: line 212: deactivate: No such file or directory
Finished the preprocessing step!
Running the context-independent pore model...
Traceback (most recent call last):
  File "/home/anjalid/DeepSimulator/pore_model/src/kmer_simulator.py", line 1, in <module>
    from poremodel_util import *
  File "/home/anjalid/DeepSimulator/pore_model/src/poremodel_util.py", line 1, in <module>
    import numpy as np
ImportError: No module named numpy
Finished generate the simulated signals!
Converting the signal into FAST5 files...
Traceback (most recent call last):
  File "/home/anjalid/DeepSimulator/util/fast5_modify_signal.py", line 1, in <module>
    import h5py
  File "/home/anjalid/.local/lib/python2.7/site-packages/h5py/__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5t.pxd", line 14, in init h5py._conv
  File "h5py/numpy.pxd", line 66, in init h5py.h5t
ImportError: No module named numpy
Finished format converting!
Running Albacore...
Basecalling finished!
Checking the read accuracy...
cat: '/home/anjalid/DeepSimulator/artificial_human_chr22_DeepSimu/fastq/workspace/pass/*.fastq': No such file or directory
[M::mm_idx_gen::0.142*1.04] collected minimizers
[M::mm_idx_gen::0.177*1.84] sorted minimizers
[M::main::0.177*1.84] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.186*1.80] mid_occ = 29
[M::mm_idx_stat] kmer size: 19; skip: 10; is_HPC: 1; #seq: 1
[M::mm_idx_stat::0.193*1.77] distinct minimizers: 120625 (97.76% are singletons); average occurrences: 1.067; average spacing: 7.771
[M::main] Version: 2.2-r479-dirty
[M::main] CMD: /home/anjalid/DeepSimulator/util/minimap2 -Hk19 -t 8 -c /home/anjalid/DeepSimulator/example/artificial_human_chr22.fasta /home/anjalid/DeepSimulator/artificial_human_chr22_DeepSimu/test.fastq
[M::main] Real time: 0.212 sec; CPU: 0.361 sec
Here is the mapping identity: -nan of 0 reads passed base-calling.

**Comment by realbigws** [comment]
Have you installed all the required package by typing "./install.sh" ?
If not, please do so.

After that, you may type "source activate tensorflow_cdpm" and see what happened.

Before using the 'deep_simulator.sh' command, you may first try some simple examples, such as the Context-dependent pore model:

./pore_model.sh example/001c577a-a502-43ef-926a-b883f94d157b.true_fasta 0

**Comment by dhallanjali** [comment]
The issue is resolved, thank you so much for your help.
